county_ids:
    Taipei: 454
    Keelung: 453
    NewTaipei: 455
    Taoyuan: 456
    HsinchuCity: 457
    HsinchuCounty: 458
    Miaoli: 459
    Taichung: 460
    Changhua: 462
    Nantou: 463
    Yunlin: 464
    ChiayiCity: 465
    ChiayiCounty: 466
    Tainan: 467
    Kaohsiung: 469
    Pingtung: 471
    Taitung: 472
    Hualien: 473
    Yilan: 474
    All: 356
